apiVersion: v1
kind: Pod 
metadata: 
  name: lb-pod
  labels: 
    app: myapp 
    env: devops
spec: 
  containers: 
  - name: tomcat-container
    image: tomcat:latest
    ports: 
    - name: tomcatport
      containerPort: 8080