apiVersion: v1
kind: Pod 
metadata: 
  name: np-pod
  labels: 
    app: myapp  
    env: devops
  namespace: dev
spec: 
  containers: 
  - name: httpd-container
    image: httpd:latest 
    ports: 
    - name: httpdport
      containerPort: 80 