apiVersion: v1 
kind: Service 
metadata: 
  name: deployment-svc 
  labels: 
    app: myapp 
  namespace: autoscaling 
spec: 
  type: NodePort 
  selector: 
    app: myapp 
  ports: 
  - name: deployment-svc-port 
    protocol: TCP 
    port: 80
    targetPort: 80